
$(top_srcdir)/ext/mailparse/php_mailparse_rfc822.c: $(top_srcdir)/ext/mailparse/php_mailparse_rfc822.re
	re2c -b $(top_srcdir)/ext/mailparse/php_mailparse_rfc822.re > $@

/ibm/cct6/adhoc/email/mailparse-2.1.5/php_mailparse_rfc822.c: /ibm/cct6/adhoc/email/mailparse-2.1.5/php_mailparse_rfc822.re
	re2c -b /ibm/cct6/adhoc/email/mailparse-2.1.5/php_mailparse_rfc822.re > $@

